comentar codigo

diff --git a/bin/validate_push b/bin/validate_push
--- a/bin/validate_push
+++ b/bin/validate_push
@@ -2,12 +2,12 @@
 
 # script prevents pushing to develop and master by mistake
 exit
-branch="$(git rev-parse --abbrev-ref HEAD)"
+# branch="$(git rev-parse --abbrev-ref HEAD)"
 
-if [ "$branch" = "master" ]; then
-  echo "You can't push directly to master branch"
-  exit 1
-elif [ "$branch" = "develop" ]; then
-  echo "You can't push directly to develop branch"
-  exit 1
-fi
+# if [ "$branch" = "master" ]; then
+#   echo "You can't push directly to master branch"
+#   exit 1
+# elif [ "$branch" = "develop" ]; then
+#   echo "You can't push directly to develop branch"
+#   exit 1
+# fi
